### ISSUE TITLE
Make requesting winegcc

### ISSUE THREAD

**Issue by embeddedfreedom** [brentr/wineftd2xx#12]
make requesting winegcc. 

WINEDLLPATH=/usr/lib/wine
Link with libftd2xx1.1.12/build/x86_64/libftd2xx.a
wget http://www.ftdichip.com/Drivers/D2XX/Linux/libftd2xx1.1.12.tar.gz
--2022-03-01 16:49:40--  http://www.ftdichip.com/Drivers/D2XX/Linux/libftd2xx1.1.12.tar.gz
Resolving www.ftdichip.com (www.ftdichip.com)... 217.160.0.88, 2001:8d8:100f:f000::2e7
Connecting to www.ftdichip.com (www.ftdichip.com)|217.160.0.88|:80... connected.
HTTP request sent, awaiting response... 200 OK
Length: 950540 (928K) [application/gzip]
Saving to: ‘libftd2xx1.1.12.tar.gz’

libftd2xx1.1.12.tar 100%[===================>] 928.26K   667KB/s    in 1.4s    

2022-03-01 16:49:42 (667 KB/s) - ‘libftd2xx1.1.12.tar.gz’ saved [950540/950540]

touch -t 1201010000 libftd2xx1.1.12.tar.gz
tar xzf libftd2xx1.1.12.tar.gz
rm -rf libftd2xx1.1.12
mv release libftd2xx1.1.12
sed "s/WINAPI FT_/xFT_/g" libftd2xx1.1.12/ftd2xx.h >xftd2xx.h
winegcc -D_REENTRANT -D__WINESRC__ -c -g -O0 -Wall -m64 \
          -Ilibftd2xx1.1.12 -fno-omit-frame-pointer -o ftd2xx.o ftd2xx.c
make: winegcc: Command not found
make: *** [Makefile:62: ftd2xx.o] Error 127

My Wine version is 

dipto@dipto-VirtualBox:~/Desktop/Cortex_M4/wineftd2xx-master$ wine --version
wine-5.0 (Ubuntu 5.0-3ubuntu1)

**Comment by brentr** [comment]
You need to install the wine development tools.  Please see:

https://command-not-found.com/winegcc

**Comment by embeddedfreedom** [comment]
Make and Make install went through, however with apt-get install wine64-tools on my Linux Mint 20.2. 
apt-get install wine1.6  returned without a package. IMHO, information on winegcc install should a part of the wineftd2xx README as it does not look to be a very familiar package to those seldom using Wine. Like for me its only to run Notepad++ and LogicPort software.

Thank you. Closing this.
