### ISSUE TITLE
Running 64bits executable

### ISSUE THREAD

**Issue by calandoa** [brentr/wineftd2xx#5]
Hello,

When running this wrapper with an executable compiled on Windows with Mingw 32bits gcc, the calls are executed as expected.

However, when the same executable is compiled with 64bits gcc, I do not get the expected behavior.  The calls are failing, probably because there is a mismatch with pointers.

For instance, FT_CreateDeviceInfoList(&num_device) should just return the number of connected devices in the int pointer. The first case is OK, but in the second one, my variable is not updated.

I checked with strace what is happening, and I can see the system calls dealing with /sys/bus/usb occuring and been identical in both cases... but it looks like some mess occurs at the moment the code write the result in the variable designated by the given pointer.

Do you have any idea how I can correct this problem?

**Comment by calandoa** [comment]
I finally found the problem: the calls to the legacy linux lib FTD2xx were done using the MS ABI, because of a problem in the Makefile: In the generated file `xftd2xx.h`, `WINAPI` get translated to `__stdcall`, then to `__attribute__((ms_abi))`.

The Wine's include files show this bug is probably occurring due to the use of x86_64 target.

The patch is to change:
```
xftd2xx.h:  $(IDIR)/ftd2xx.h Makefile
	sed "s/WINAPI FT_/WINAPI xFT_/g" $(IDIR)/ftd2xx.h >$@
```
to:
```
xftd2xx.h:  $(IDIR)/ftd2xx.h Makefile
	sed "s/WINAPI FT_/xFT_/g" $(IDIR)/ftd2xx.h >$@
```

**Comment by brentr** [comment]
Thank you for finding and fixing this.
I don't run any x86_64 versions of wine.  All mine are i386 for very old development tools.
Could you please verify the patch on your system?

**Comment by calandoa** [comment]
I have just tested it, it is ok.

There is a few other problems with Makefile paths when using Ubuntu's 18.04 wine package, but these are trivial to fix.
